// Auto-generated by build_cards.py
#pragma once

constexpr int ID_ASCENSION_BOW = 106;
constexpr int ID_SUPER_MIRROR = 184;
constexpr int ID_EXCHANGE = 185;
constexpr int ID_SELL = 186;
constexpr int ID_BUY = 187;
constexpr int ID_SUN_AMULET = 205;
