import os
import yaml
import json

def build_cards():
    input_dir = 'assets/cards'
    output_json = 'assets/godfield_cards.json'
    
    # We load files in alphabetical order
    files = sorted([f for f in os.listdir(input_dir) if f.endswith('.yaml')])
    
    all_cards = []
    
    for filename in files:
        filepath = os.path.join(input_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)
            if data:
                all_cards.extend(data)
                
    # Assign sequential IDs
    for i, card in enumerate(all_cards):
        card['id'] = i
        
    with open(output_json, 'w', encoding='utf-8') as f:
        json.dump(all_cards, f, ensure_ascii=False, indent=2)
        
    # Generate C++ header for card IDs
    header_path = 'godfield_core/src/generated_card_ids.h'
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by build_cards.py\n")
        f.write("#pragma once\n\n")
        for card in all_cards:
            if 'id_str' in card and card['id_str']:
                base_name = os.path.basename(card['id_str'])
                base_id = os.path.splitext(base_name)[0]
                macro_name = f"ID_{base_id.upper().replace('-', '_')}"
                f.write(f"constexpr int {macro_name} = {card['id']};\n")
                
    print(f"Successfully built {len(all_cards)} cards into {output_json} and {header_path}")

if __name__ == "__main__":
    build_cards()
